### ISSUE TITLE
Consul template is not reading token in $HOME./vault

### ISSUE THREAD

**Issue by hayoade1** [hashicorp/vault-guides#100]
I tried following the example in vault-agent-k8s-demo using gke instead of minikube. Consul-template container keeps failing, and when I run "kubectl logs vault-agent-example consul-template", I see the following error in the logs:

2019/01/01 16:18:14.061809 [WARN] (view) vault.read(secret/myapp/config): vault.read(secret/myapp/config): Error making API request.

URL: GET http://xx.xxx.xx.xx:8200/v1/secret/myapp/config
Code: 400. Errors:

* missing client token (retry attempt 4 after "8s")

I'm able to see the token when I exec into the vault-agent container with the following commands

$ kubectl exec -it vault-agent-example --container vault-agent-auth sh

/# echo $(cat /home/vault/.vault-token)

Also, I'm able to successfully authenticate with the token obtain with the command above using the CLI.

The consul template container also works when I hard code a valid token in the nano example-k8s-spec.yml as an environment variable.

all files in the repo were unaltered except for the nano example-k8s-spec.yml file as I had to point the Vault url to my vault service.

**Comment by hayoade1** [comment]
@yhyakuna thanks for your comment. Its V1. See output of the command below:

secret/       kv           kv_8c508b53           system         system     false                                                                                          replicated     false        map[version:1]    key/value secret stor

**Comment by yhyakuna** [comment]
@hayoade1   I was able to reproduce the error.  It seems that `.vault_token` is not a shared data in a **GKE** cluster while it was reachable from consul-template container in **minikube**.

To make this work, the `sink` must be modified to write the token as a shared data.  The current vault agent configuration (`vault-agent-config.hcl`) is:
```
...
    sink "file" {
        config = {
            path = "/home/vault/.vault-token"
        }
    }
```

@tdsacilowski   Do you have other comment/insight on this?

**Comment by hayoade1** [comment]
@yhyakuna and  @tdsacilowski how can I configure the sink to write the token as a shared data? I do not see any info on it in the vault agent documentation.
Thank you for your assistance.

**Comment by yhyakuna** [comment]
@hayoade1   Reviewing the `example-k8s-spec.yml`, it is correctly setting the `/home/vault` to be a _shared_ storage between the vault-agent-auth and consul-template containers (see line 35 & 60), so there's no reason why the Consul Template cannot read the token from `/home/vault/.vault_token` file.  (It's not the `sink` setting.  The sink **path** needs to point to a shared storage so that other containers in the pod can read.)  

So, I'm puzzled :(   

```
...
  containers:
    # Vault container
    - name: vault-agent-auth
      image: vault

      volumeMounts:
        - name: vault-token
          mountPath: /home/vault
       ...
     
    # Consul Template container
    - name: consul-template
      image: hashicorp/consul-template
      imagePullPolicy: Always

      volumeMounts:
        - name: vault-token
          mountPath: /home/vault
...
```

The fact that this works fine with minikube, this must be a GKE issue???

I'm a kubernetes beginner myself, so need to do some more research on GKE.  FYI, this [article](https://www.stratoscale.com/blog/kubernetes/kubernetes-how-to-share-disk-storage-between-containers-in-a-pod/) explains creating shared storage in a pod.

**Comment by yhyakuna** [comment]
I tried what @hayoade1  did and set the VAULT_TOKEN environment variable in `example-k8s-spec.yml`:

```
...
    # Consul Template container
    - name: consul-template
      image: hashicorp/consul-template
      imagePullPolicy: Alway

     ...

      env:
        - name: VAULT_TOKEN
          value: $(cat /home/vault/.vault-token)
          ...
```

Now, I'm getting `error performing token check` error instead of missing client token error. :(
